name: Test

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test e2e
    runs-on: ubuntu-latest
    if: !contains(github.event.head_commit.message, 'skip test')
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
          
      - run: cp .env.test .env

      - run: npm ci

      - name: Cache imagemin
        uses: actions/cache@v3
        with:
          path: tmp/gulp-cache/imagemin
          key: gulp-imagemin-${{ hashFiles('node_modules/imagemin-?*/package.json') }}

      - name: Test
        run: npm run test
        
      - name: Upload failed tests
        if: failure() && github.event_name == 'pull_request'
        uses: edunad/actions-image@v1.0.1
        with:
          path: './tmp/test-failed/*.jpg'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: 'Failed E2E tests 🙀'
